# Generated by Django 4.2.3 on 2023-07-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hero_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='client_logo/')),
                ('website', models.URLField(blank=True)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
    ]
